### ISSUE TITLE
Compatibility issue Climate Control/Geographicraft mod

### ISSUE THREAD

**Issue by ghost** [superbas11/MenuMobs#21]
click options, come back; no mobs... click single player, come back: no mobs... anywhere...
using game 1.11.2 forge 2223 and latest version of mod.

**Comment by bschoenmaeckers** [comment]
Do you have any error message in your game log/console?

**Comment by ghost** [comment]
ahh sorry, it is only happening when clicking multiplayer tab. and no, no any error.

**Comment by ghost** [comment]
**AND, it sometimes doesn't work then opening the game. here is my latest log. i see some errors.**
[23:37:07] [Client thread/ERROR]: Using missing texture, unable to load techreborn:textures/blocks/fluids/electrolyzedwater_flowing.png, java.io.FileNotFoundException
[23:37:07] [Client thread/ERROR]: Using missing texture, unable to load techreborn:textures/blocks/fluids/carbon_flowing.png, java.io.FileNotFoundException
[23:37:07] [Client thread/ERROR]: Using missing texture, unable to load techreborn:textures/blocks/machines/generators/semi_fluid_generator_top_on.png, java.io.FileNotFoundException
[23:37:07] [Client thread/ERROR]: Using missing texture, unable to load techreborn:textures/blocks/fluids/sulfur_flowing.png, java.io.FileNotFoundException
[23:37:07] [Client thread/ERROR]: Using missing texture, unable to load techreborn:textures/blocks/fluids/nitrodiesel_flowing.png, java.io.FileNotFoundException
[23:37:07] [Client thread/ERROR]: Using missing texture, unable to load techreborn:textures/blocks/fluids/compressedair_flowing.png, java.io.FileNotFoundException
[23:37:08] [Client thread/ERROR]: Using missing texture, unable to load techreborn:textures/items/cell_empty.png, java.io.FileNotFoundException
[23:37:08] [Client thread/ERROR]: Using missing texture, unable to load techreborn:textures/items/misc/missing_recipe.png, java.io.FileNotFoundException
[23:37:08] [Client thread/ERROR]: Using missing texture, unable to load techreborn:textures/blocks/machines/generators/semi_fluid_generator_bottom.png, java.io.FileNotFoundException
[23:37:08] [Client thread/ERROR]: Using missing texture, unable to load techreborn:textures/blocks/fluids/carbonfiber_flowing.png, java.io.FileNotFoundException
[23:37:08] [Client thread/ERROR]: Using missing texture, unable to load techreborn:textures/blocks/fluids/diesel_flowing.png, java.io.FileNotFoundException
[23:37:08] [Client thread/ERROR]: Using missing texture, unable to load embers:textures/textures/blocks/pipe_tex.png.png, java.io.FileNotFoundException
[23:37:08] [Client thread/ERROR]: Using missing texture, unable to load techreborn:textures/blocks/machines/generators/semi_fluid_generator_side_on.png, java.io.FileNotFoundException
[23:37:08] [Client thread/ERROR]: Using missing texture, unable to load techreborn:textures/blocks/fluids/wolframium_flowing.png, java.io.FileNotFoundException
[23:37:08] [Client thread/ERROR]: Using missing texture, unable to load techreborn:textures/blocks/fluids/nitrocarbon_flowing.png, java.io.FileNotFoundException
[23:37:08] [Client thread/ERROR]: Using missing texture, unable to load techreborn:textures/blocks/fluids/sulfuricacid_flowing.png, java.io.FileNotFoundException
[23:37:08] [Client thread/ERROR]: Using missing texture, unable to load techreborn:textures/blocks/fluids/sodiumsulfide_flowing.png, java.io.FileNotFoundException
[23:37:08] [Client thread/INFO]: Created: 2048x1024 textures-atlas
[23:37:10] [Client thread/WARN]: Unable to resolve texture due to upward reference: #all in minecraft:models/block/cube_all
[23:37:10] [Client thread/WARN]: Unable to resolve texture due to upward reference: #all in minecraft:models/block/cube_all
[23:37:10] [Client thread/WARN]: Unable to resolve texture due to upward reference: #all in minecraft:models/block/cube_all
[23:37:10] [Client thread/WARN]: Unable to resolve texture due to upward reference: #all in minecraft:models/block/cube_all
[23:37:10] [Client thread/WARN]: Unable to resolve texture due to upward reference: #all in minecraft:models/block/cube_all
[23:37:10] [Client thread/WARN]: Unable to resolve texture due to upward reference: #all in minecraft:models/block/cube_all
[23:37:10] [Client thread/WARN]: Unable to resolve texture due to upward reference: #all in minecraft:models/block/cube_all
[23:37:10] [Client thread/WARN]: Unable to resolve texture due to upward reference: #all in minecraft:models/block/cube_all
[23:37:10] [Client thread/WARN]: Unable to resolve texture due to upward reference: #all in minecraft:models/block/cube_all
[23:37:10] [Client thread/WARN]: Unable to resolve texture due to upward reference: #all in minecraft:models/block/cube_all
[23:37:10] [Client thread/WARN]: Unable to resolve texture due to upward reference: #all in minecraft:models/block/cube_all
[23:37:10] [Client thread/WARN]: Unable to resolve texture due to upward reference: #all in minecraft:models/block/cube_all
[23:37:10] [Client thread/WARN]: Unable to resolve texture due to upward reference: #all in minecraft:models/block/cube_all
[23:37:10] [Client thread/WARN]: Unable to resolve texture due to upward reference: #all in minecraft:models/block/cube_all
[23:37:11] [Client thread/WARN]: Skipping bad option: lastServer:
[23:37:11] [Client thread/INFO]: [STDERR]: java.lang.NullPointerException
[23:37:11] [Client thread/INFO]: [STDERR]: 	at java.lang.Class.isAssignableFrom(Native Method)
[23:37:11] [Client thread/INFO]: [STDERR]: 	at superbas11.menumobs.client.util.EntityUtils.getRandomLivingEntity(EntityUtils.java:240)
[23:37:11] [Client thread/INFO]: [STDERR]: 	at superbas11.menumobs.MainMenuRenderTicker.init(MainMenuRenderTicker.java:553)
[23:37:11] [Client thread/INFO]: [STDERR]: 	at superbas11.menumobs.MainMenuRenderTicker.onTick(MainMenuRenderTicker.java:420)
[23:37:11] [Client thread/INFO]: [STDERR]: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_403_MainMenuRenderTicker_onTick_RenderTickEvent.invoke(.dynamic)
[23:37:11] [Client thread/INFO]: [STDERR]: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
[23:37:11] [Client thread/INFO]: [STDERR]: 	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
[23:37:11] [Client thread/INFO]: [STDERR]: 	at net.minecraftforge.fml.common.FMLCommonHandler.onRenderTickStart(FMLCommonHandler.java:353)
[23:37:11] [Client thread/INFO]: [STDERR]: 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1075)
[23:37:11] [Client thread/INFO]: [STDERR]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:372)
[23:37:11] [Client thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(SourceFile:124)
[23:37:11] [Client thread/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[23:37:11] [Client thread/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[23:37:11] [Client thread/INFO]: [STDERR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[23:37:11] [Client thread/INFO]: [STDERR]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[23:37:11] [Client thread/INFO]: [STDERR]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[23:37:11] [Client thread/INFO]: [STDERR]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[23:37:11] [Client thread/INFO]: [STDERR]: java.lang.NullPointerException
[23:37:11] [Client thread/INFO]: [STDERR]: 	at net.minecraft.client.renderer.entity.RenderManager.func_180597_a(RenderManager.java:318)
[23:37:11] [Client thread/INFO]: [STDERR]: 	at superbas11.menumobs.MainMenuRenderTicker.onTick(MainMenuRenderTicker.java:424)
[23:37:11] [Client thread/INFO]: [STDERR]: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_403_MainMenuRenderTicker_onTick_RenderTickEvent.invoke(.dynamic)
[23:37:11] [Client thread/INFO]: [STDERR]: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
[23:37:11] [Client thread/INFO]: [STDERR]: 	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
[23:37:11] [Client thread/INFO]: [STDERR]: 	at net.minecraftforge.fml.common.FMLCommonHandler.onRenderTickStart(FMLCommonHandler.java:353)
[23:37:11] [Client thread/INFO]: [STDERR]: 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1075)
[23:37:11] [Client thread/INFO]: [STDERR]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:372)
[23:37:11] [Client thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(SourceFile:124)
[23:37:11] [Client thread/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[23:37:11] [Client thread/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[23:37:11] [Client thread/INFO]: [STDERR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[23:37:11] [Client thread/INFO]: [STDERR]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[23:37:11] [Client thread/INFO]: [STDERR]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[23:37:11] [Client thread/INFO]: [STDERR]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[23:37:12] [Snooper Timer/INFO]: [STDOUT]: --------------------> Reached Target Method (PORT) !
[23:45:52] [Client thread/INFO]: Stopping!
[23:45:52] [Client thread/INFO]: SoundSystem shutting down...

**Comment by bschoenmaeckers** [comment]
Can you enable debug mode in the MenuMobs config and send me the full fml-log please?

**Comment by bschoenmaeckers** [comment]
Use pastebin.com of gist.github.com to send your log.

**Comment by ghost** [comment]
i just enabled the debug mode(debug output=true) and uninstalled my shaderpack. these things are the only things that i did. opened the game, and it's working now. i don't know anything else. i can send the fml-log if you still wish.

**Comment by bschoenmaeckers** [comment]
I think I found what causes it. Can you confirm it by trying it multiple times?

**Comment by ghost** [comment]
yeah i tried a lot. ahhhh yes it happened again, it's not working right now. no mobs on the title screen after closing my world. want me send the log file?

**Comment by ghost** [comment]
[fml-client-latest.txt](https://github.com/superbas11/MenuMobs/files/717928/fml-client-latest.txt)
here is latest fml log

**Comment by bschoenmaeckers** [comment]
did you enable debug mode in the menu mobs config?

**Comment by ghost** [comment]
yes i did
![debug](https://cloud.githubusercontent.com/assets/24831406/22128088/aec0cd90-dea7-11e6-82f9-bf71303fa159.PNG)

**Comment by bschoenmaeckers** [comment]
ok thanks, I see the problem. Going to fix it right away!

**Comment by ghost** [comment]
thank you too. :)

**Comment by bschoenmaeckers** [comment]
This is an compatibility issue with Climate Control/Geographicraft mod. I'm looking what I can do to fix it but I haven't found a solution on my side yet. Can you make a bug report on their side too please?

**Comment by ghost** [comment]
omg, are you sure it is about geographicraft mod? these mods are really different worlds each other.

**Comment by bschoenmaeckers** [comment]
yeah I'm sure.

**Comment by bschoenmaeckers** [comment]
btw, when you download the latest release it should fix the other problems you had, except the crash that you SOMETIMES had when you leave a world.

**Comment by ghost** [comment]
oh okay, thanks a lot.
by the way; i reported the issue to the geographicraft github.

**Comment by bschoenmaeckers** [comment]
Thank you.

**Comment by bschoenmaeckers** [comment]
should be fixed in version 1.17.

**Comment by ghost** [comment]
thanks a lot
